### ISSUE TITLE
Import statement freezes the process

### ISSUE THREAD

**Issue by droooney** [xiaofuzi/rollup-plugin-less#1]
It seems that import statement blocks the process.

**Comment by xiaofuzi** [comment]
Could you describe more detail?

**Comment by droooney** [comment]
This is basically all of it :)

If I write one less file with
```less
// mixins.less

.hidden {
  display: none !important;
}
```

and another one with
```less
// main.less

@import './mixins.less';

.elem {
  .hidden();
}
```

This freezes rollup process. Specifically, rollup-watch one.
